# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1485719777);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1485719897);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1485719537);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 1485720137);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1485719657);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1485719417);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1485720017);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1485722813662");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1485724575662");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1485722925834");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1485726525834");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160802213348");
user_pref("browser.slowStartup.averageTime", 6830);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20160802213348");
user_pref("browser.startup.homepage_override.mstone", "45.3.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1485462815608");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1485377109033");
user_pref("datareporting.policy.firstRunTime", "1485376415607");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.firstPaint", 8005);
user_pref("datareporting.sessions.current.main", 1164);
user_pref("datareporting.sessions.current.sessionRestored", 8088);
user_pref("datareporting.sessions.current.startTime", "1485749931843");
user_pref("datareporting.sessions.current.totalTime", 36);
user_pref("datareporting.sessions.currentIndex", 16);
user_pref("datareporting.sessions.previous.15", "{\"s\":1485719293114,\"a\":413,\"t\":3694,\"c\":true,\"m\":1209,\"fp\":7660,\"sr\":7845}");
user_pref("datareporting.sessions.prunedIndex", 14);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 5);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.3.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1485719778);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.3.0");
user_pref("extensions.lastPlatformVersion", "45.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1470173628000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.3.0\",\"st\":1470173628000}}}");
user_pref("gecko.buildID", "20160802213348");
user_pref("gecko.mstone", "45.3.0");
user_pref("gfx.crash-guard.glcontext.appVersion", "45.3.0");
user_pref("gfx.crash-guard.glcontext.deviceID", "Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) x86/MMX/SSE2");
user_pref("gfx.crash-guard.glcontext.driverVersion", "3.0 Mesa 11.2.2");
user_pref("gfx.crash-guard.status.glcontext", 2);
user_pref("idle.lastDailyNotification", 1485658345);
user_pref("media.gmp-manager.buildID", "20160802213348");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1485378349);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1485378349);
user_pref("toolkit.startup.last_success", 1485749933);
user_pref("toolkit.telemetry.cachedClientID", "b5bfe697-e817-4059-809d-bf24f112a64e");
user_pref("toolkit.telemetry.previousBuildID", "20160802213348");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
